name: your_notes
description: Your Notes is an app to keep your notes with you all time
version: 0.1.0

publish_to: 'none'

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../design_system

  dependencies:
    path: ../dependencies

  core:
    path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
